development:
  sessions:
    default:
      uri: mongodb://rubish:password@ds037617-a.mongolab.com:37617/heroku_app7694746
      options:
        consistency: :strong

  options:

production:
  sessions:
    default:
      uri: mongodb://rubish:password@ds037617-a.mongolab.com:37617/heroku_app7694746
      options:
        consistency: :strong
