development:
  sessions:
    default:
      uri: mongodb://rubish:password@ds037617-a.mongolab.com:37617/heroku_app7694746
      options:
        consistency: :strong

test:
  sessions:
    default:
      uri: mongodb://rubish:password@ds037617-a.mongolab.com:37617/heroku_app7694746
    options:
      skip_version_check: true
      safe: true

production:
  sessions:
    default:
      uri: mongodb://rubish:password@ds037617-a.mongolab.com:37617/heroku_app7694746
    options:
      skip_version_check: true
      safe: true

