development:
  sessions:
    default:
      uri: mongodb://rubish:pass@ds037627-a.mongolab.com:37627/almaconnect-test-db
      options:
        consistency: :strong
  options:
test:
  sessions:
    default:
      uri: mongodb://rubish:pass@ds037627-a.mongolab.com:37627/almaconnect-test-db
      options:
        consistency: :strong
production:
  sessions:
    default:
      uri: mongodb://rubish:pass@ds037627-a.mongolab.com:37627/almaconnect-test-db
      options:
        skip_version_check: true
        safe: true