development:
  sessions:
    default:
      uri: mongodb://<user>:<password>@ds037617-a.mongolab.com:37617/heroku_app7694746
      options:
        consistency: :strong
  options:
test:
  sessions:
    default:
      uri: mongodb://<user>:<password>@ds037617-a.mongolab.com:37617/heroku_app7694746
      options:
        consistency: :strong
production:
  sessions:
    default:
      uri: mongodb://<user>:<password>@ds037617-a.mongolab.com:37617/heroku_app7694746
      options:
        consistency: :strong

